#!/usr/bin/env bash
# Generate .env for compose — stable secrets only.
# AWS credentials are NOT written here; litellm-proxy runs on the internal_net
# bridge network and boto3 fetches them from the EC2 IMDS at runtime (no expiry
# problem). Requires HttpPutResponseHopLimit >= 2 on the EC2 instance metadata
# options — the container-to-host NAT hop is otherwise invisible to a
# hop-limit-1 IMDSv2 token request.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

# Preserve stable secrets across regenerations
POSTGRES_PASSWORD=""
LITELLM_MASTER_KEY=""
EXISTING_DATABASE_URL=""
if [[ -f "${ENV_FILE}" ]]; then
    POSTGRES_PASSWORD=$(grep "^POSTGRES_PASSWORD=" "${ENV_FILE}" 2>/dev/null | cut -d= -f2- || true)
    LITELLM_MASTER_KEY=$(grep "^LITELLM_MASTER_KEY=" "${ENV_FILE}" 2>/dev/null | cut -d= -f2- || true)
    EXISTING_DATABASE_URL=$(grep "^DATABASE_URL=" "${ENV_FILE}" 2>/dev/null | cut -d= -f2- || true)
fi
[[ -z "${POSTGRES_PASSWORD}" ]] && POSTGRES_PASSWORD=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')
[[ -z "${LITELLM_MASTER_KEY}" ]] && LITELLM_MASTER_KEY="sk-$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"

VOLUMES="${VOLUMES:-${HOME}/Build/Volumes}"

# DATABASE_URL: preserve whatever's already in .env (covers a manual switch
# to Amazon RDS — see rds-postgres.yaml), else honor an explicit env var,
# else default to the local litellm-db container.
if [[ -n "${EXISTING_DATABASE_URL}" ]]; then
    DATABASE_URL="${EXISTING_DATABASE_URL}"
elif [[ -n "${DATABASE_URL:-}" ]]; then
    DATABASE_URL="${DATABASE_URL}"
else
    DATABASE_URL="postgresql://proxy_admin:${POSTGRES_PASSWORD}@litellm-db:5432/litellm"
fi

cat > "${ENV_FILE}" <<EOF
# Auto-generated by gen-env.sh — do not edit by hand
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
DATABASE_URL=${DATABASE_URL}
VOLUMES=${VOLUMES}
EOF

chmod 600 "${ENV_FILE}"
echo "[gen-env] .env written."
echo "[gen-env] LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}"
