#!/usr/bin/env bash
# Scanner-agnostic container image scan: vulnerability gate + optional
# Dockerfile/config misconfiguration check + optional SBOM generation.
#
# Deliberately does NOT build the image — the caller (a human, or any CI
# system) builds/pulls it first. That's what makes this runnable from any
# pipeline, or straight from a terminal, without assuming GitHub Actions or
# any single scanner tool.
#
# No specific scanner is required by this repo. Trivy is the default only
# because it's a reasonable single default, not because it's mandated —
# swap it via SCANNER, or bypass this script's tool assumptions entirely via
# SCANNER=custom.
#
# Usage:
#   scan-image.sh --image <ref> [--context <dir>] [--sbom-out <file>] \
#                  [--severity CRITICAL,HIGH] [--ignore-unfixed true|false]
#
# Env vars:
#   SCANNER       trivy (default) | grype | custom
#   SCANNER_CMD   required when SCANNER=custom — a command template with a
#                 literal "{IMAGE}" placeholder, e.g.:
#                 SCANNER_CMD='mytool scan --fail-on high {IMAGE}'
#
# Exit codes:
#   0  scan ran, no findings at/above the severity threshold
#   1  scan ran, findings at/above the severity threshold were found
#   2  usage or configuration error (bad args, scanner binary missing)
#   3  the scanner itself errored unexpectedly (distinct from "found vulns")
set -euo pipefail

SCANNER="${SCANNER:-trivy}"
SEVERITY="CRITICAL,HIGH"
IGNORE_UNFIXED="true"
IMAGE=""
CONTEXT_DIR=""
SBOM_OUT=""

usage() {
    cat >&2 <<EOF
Usage: $0 --image <ref> [--context <dir>] [--sbom-out <file>] \\
          [--severity CRITICAL,HIGH] [--ignore-unfixed true|false]

Env: SCANNER=trivy|grype|custom (default: trivy), SCANNER_CMD (SCANNER=custom only)
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --image) IMAGE="$2"; shift 2 ;;
        --context) CONTEXT_DIR="$2"; shift 2 ;;
        --sbom-out) SBOM_OUT="$2"; shift 2 ;;
        --severity) SEVERITY="$2"; shift 2 ;;
        --ignore-unfixed) IGNORE_UNFIXED="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; usage; exit 2 ;;
    esac
done

if [[ -z "${IMAGE}" ]]; then
    echo "ERROR: --image is required." >&2
    usage
    exit 2
fi

IGNORE_UNFIXED_FLAG=""
[[ "${IGNORE_UNFIXED}" == "true" ]] && IGNORE_UNFIXED_FLAG="--ignore-unfixed"

FINDINGS=0

run_trivy() {
    command -v trivy >/dev/null 2>&1 || {
        echo "ERROR: SCANNER=trivy but 'trivy' is not on PATH." >&2
        echo "  Install: https://aquasecurity.github.io/trivy/latest/getting-started/installation/" >&2
        exit 2
    }

    if [[ -n "${CONTEXT_DIR}" ]]; then
        echo "[scan-image] Dockerfile/config scan: ${CONTEXT_DIR}"
        if ! trivy config --exit-code 1 --severity "${SEVERITY}" "${CONTEXT_DIR}"; then
            FINDINGS=1
        fi
    fi

    echo "[scan-image] Vulnerability scan: ${IMAGE}"
    if ! trivy image --exit-code 1 --severity "${SEVERITY}" ${IGNORE_UNFIXED_FLAG} "${IMAGE}"; then
        FINDINGS=1
    fi

    if [[ -n "${SBOM_OUT}" ]]; then
        echo "[scan-image] SBOM (SPDX): ${SBOM_OUT}"
        trivy image --format spdx-json --output "${SBOM_OUT}" "${IMAGE}"
    fi
}

run_grype() {
    command -v grype >/dev/null 2>&1 || {
        echo "ERROR: SCANNER=grype but 'grype' is not on PATH." >&2
        echo "  Install: https://github.com/anchore/grype#installation" >&2
        exit 2
    }

    if [[ -n "${CONTEXT_DIR}" ]]; then
        echo "[scan-image] WARNING: grype does not support Dockerfile/config" \
             "scanning — skipping --context (${CONTEXT_DIR})." >&2
    fi

    echo "[scan-image] Vulnerability scan: ${IMAGE}"
    if ! grype "${IMAGE}" --fail-on "$(echo "${SEVERITY}" | cut -d, -f1)"; then
        FINDINGS=1
    fi

    if [[ -n "${SBOM_OUT}" ]]; then
        if command -v syft >/dev/null 2>&1; then
            echo "[scan-image] SBOM (SPDX) via syft: ${SBOM_OUT}"
            syft "${IMAGE}" -o spdx-json="${SBOM_OUT}"
        else
            echo "[scan-image] WARNING: --sbom-out requested but 'syft' is not" \
                 "on PATH — skipping SBOM generation." >&2
        fi
    fi
}

run_custom() {
    [[ -z "${SCANNER_CMD:-}" ]] && {
        echo "ERROR: SCANNER=custom requires SCANNER_CMD to be set." >&2
        exit 2
    }
    local cmd="${SCANNER_CMD//\{IMAGE\}/${IMAGE}}"
    echo "[scan-image] Custom scanner: ${cmd}"
    if ! eval "${cmd}"; then
        FINDINGS=1
    fi
    [[ -n "${CONTEXT_DIR}" ]] && echo "[scan-image] NOTE: --context is not used by SCANNER=custom." >&2
    [[ -n "${SBOM_OUT}" ]] && echo "[scan-image] NOTE: --sbom-out is not generated by SCANNER=custom." >&2
}

case "${SCANNER}" in
    trivy) run_trivy || exit 3 ;;
    grype) run_grype || exit 3 ;;
    custom) run_custom || exit 3 ;;
    *)
        echo "ERROR: unknown SCANNER='${SCANNER}' (expected trivy|grype|custom)." >&2
        exit 2
        ;;
esac

if [[ "${FINDINGS}" -ne 0 ]]; then
    echo "[scan-image] FAIL: findings at/above severity '${SEVERITY}' for ${IMAGE}." >&2
    exit 1
fi

echo "[scan-image] PASS: no findings at/above severity '${SEVERITY}' for ${IMAGE}."
exit 0
